# Урок 6

# Системы линейных уравнений. Часть 1

## Практическое задание

### 1. Решить систему уравнений методом Гаусса:

### $\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2 \\
x_{1}+x_{2}-3x_{3}+x_{4}=4
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде расширенной матрицы:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1\\
\end{matrix}
\right|\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}$

2) Вычтем 1 строку из 3-й строки:
### $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 - 1 & 1 - 1 & -3 - (-1) & 1 - (-2)\\
\end{matrix}
\right|\begin{matrix}
0\\ 
-2\\
4 - 0\\
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
0 & 0 & -2 & 3\\
\end{matrix}
\right|\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}$

3) Умножим 1 строку на 2 и вычтем из 3-й строки:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 - 2 & 1 - 2 & -1 - (-2) & 1 - (-4) \\ 
0 & 0 & -2 & 3\\
\end{matrix}
\right|\begin{matrix}
0\\ 
-2 - 0\\
4\\
\end{matrix}
\end{pmatrix} =
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3\\
\end{matrix}
\right|\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}$

4) Разделим каждую строку матрицы на соответсвующий ведущий элемент: 1 строку на 1, 2 строку на -1, 3 строку на -2:<br>

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5 \\ 
0 & 0 & 1 & -\frac{3}{2}
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-2
\end{matrix}
\end{pmatrix}$

5) Запишем полученные коэффициенты в систему уравнений и выразим $x_{1}, x_{2}, x_{3}$:<br>
### $\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0 \\
~~~~~~~~x_{2}-x_{3}-5x_{4}=2 \\
~~~~~~~~~~~~~~~x_{3}-\frac{3}{2}x_{4}=-2
\end{cases}$

### $x_{1}=-x_{2}+x_{3}+2x_{4}$<br>
### $x_{2}=2+x_{3}+5x_{4}$<br>
### $x_{3} = -2 + \frac{3}{2}x_{4}$<br>

6) Найдем $x_{1}$ и $x_{2}$:<br>
### $x_{2}=2+x_{3}+5x_{4}=2+(-2+\frac{3}{2}x_{4})+5x_{4}=2-2+\frac{3}{2}x_{4}+\frac{10}{2}x_{4}=\frac{13}{2}x_{4}$<br>
### $x_{1}=-x_{2}+x_{3}+2x_{4}=-\frac{13}{2}x_{4}+(-2+\frac{3}{2}x_{4})+2x_{4}=-2-\frac{13}{2}x_{4}+\frac{3}{2}x_{4}+\frac{4}{2}x_{4}=-2-\frac{6}{2}x_{4}=-2-3x_{4}$

7) Запишем решение системы и найдем частное решение при $x_{4}=0$:<br>
### $\begin{cases}
x_{1}=-2-3x_{4} \\
x_{2}=\frac{13}{2}x_{4} \\
x_{3}=-2 + \frac{3}{2}x_{4}\\
x_{4}=\mathbb{R}
\end{cases} \Rightarrow
\begin{cases}
x_{1}=-2-3\cdot 0 \\
x_{2}=\frac{13}{2}\cdot 0 \\
x_{3}=-2 + \frac{3}{2}\cdot 0\\
x_{4}=0
\end{cases} \Rightarrow
\begin{cases}
x_{1}=-2 \\
x_{2}=0 \\
x_{3}=-2\\
x_{4}=0
\end{cases}$

In [1]:
import numpy as np

In [9]:
def gauss_method(A, b, n):
    rnk_A = np.linalg.matrix_rank(A)
    rnk_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    print(f'rank(A): {rnk_A}\n')
    print(f'rank(A_ext): {rnk_Ab}\n')
    print(f'N of vars: {n}\n')
    if  rnk_A == rnk_Ab == n:
        return 'Cистема совместна и имеет единственное решение'
    elif (rnk_A == rnk_Ab) and (rnk_A < n):
        return 'Cистема совместна и имеет бесконечное количество решений'
    elif rnk_A < rnk_Ab:
        return 'Cистема несовместна и не имеет решений'

In [10]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
gauss_method(A, b, 4)

rank(A): 3

rank(A_ext): 3

N of vars: 4



'Cистема совместна и имеет бесконечное количество решений'

### 2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

### а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{pmatrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1\\
\end{pmatrix};~~~~
\tilde A = \begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
4\\ 
-17\\
0\\
\end{matrix}
\end{pmatrix}$

2) Найдем ранг матрицы коэффициентов $A$. Приведем матрицу к треугольному виду:<br>

- Умножим 1-ую строку на (-2). Умножим 2-ую строку на 3. Добавим 2-ую строку к 1-ой:
### $\begin{pmatrix}
-6+6 & 2+(-15) & -2+(-9) \\ 
(2 \cdot3) & (-5 \cdot3) & (-3 \cdot3) \\ 
1 & 1 & -1\\
\end{pmatrix}=
\begin{pmatrix}
0 & -13 & -11 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1\\
\end{pmatrix}$

- Умножим 2-ую строку на (-1). Умножим 3-ую строку на (2). Добавим 3-ую строку ко 2-ой:<br>
### $\begin{pmatrix}
0 & -13 & -11 \\ 
-2+2 & 5+2 & 3+(-2) \\ 
1 & 1 & -1\\
\end{pmatrix}=
\begin{pmatrix}
0 & -13 & -11 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{pmatrix}$

- Умножим 1-ую строку на (7). Умножим 2-ую строку на (13). Добавим 2-ую строку к 1-ой:<br>
### $\begin{pmatrix}
0 + 0 & -91+91 & -77+13 \\ 
0 & (7 \cdot 13) & (1 \cdot 13) \\ 
1 & 1 & -1\\
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & -64 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{pmatrix}$

- Полученная матрица имеет размерность $3\times 3$. Наивысший порядок минора (из возможных миноров) равен 3:<br>
### $M\begin{vmatrix}
0 & 0 & -64 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{vmatrix}=-64\cdot 7 \cdot 1 = -448\ne 0 \Rightarrow rank~A = 3$ 

3) Найдем ранг расширенной матрицы $\tilde A$. Приведем матрицу к треугольному виду:<br>

- Умножим 1-ую строку на (-2). Умножим 2-ую строку на 3. Добавим 2-ую строку к 1-ой:
### $\begin{pmatrix}
\left.\begin{matrix}
-6+6 & 2+(-15) & -2+(-9) \\ 
(2 \cdot3) & (-5 \cdot3) & (-3 \cdot3) \\
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-8 + (-51)\\ 
(-17 \cdot3)\\
0\\
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
0 & -13 & -11 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-59\\ 
-17\\
0\\
\end{matrix}
\end{pmatrix}$

- Умножим 2-ую строку на (-1). Умножим 3-ую строку на (2). Добавим 3-ую строку ко 2-ой:<br>
### $\begin{pmatrix}
\left.\begin{matrix}
0 & -13 & -11 \\ 
-2+2 & 5+2 & 3+(-2) \\ 
(1\cdot 2) & (1\cdot 2) & (-1\cdot 2)\\
\end{matrix}
\right|\begin{matrix}
-59\\ 
17 + 0\\
(0\cdot 2)\\
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
0 & -13 & -11 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-59\\ 
17\\
0\\
\end{matrix}
\end{pmatrix}$

- Умножим 1-ую строку на (7). Умножим 2-ую строку на (13). Добавим 2-ую строку к 1-ой:<br>
### $\begin{pmatrix}
\left.\begin{matrix}
0 + 0 & -91+91 & -77+13 \\ 
(0 \cdot 13) & (7 \cdot 13) & (1 \cdot 13) \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-413 + 221\\ 
(17 \cdot13)\\
0\\
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & -64 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-192\\ 
17\\
0\\
\end{matrix}
\end{pmatrix}$

- Полученная матрица имеет размерность $3\times 4$. Наивысший порядок минора (из возможных миноров) равен 3:<br>
### $\tilde M
\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & -64 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{matrix}
\right|\begin{matrix}
-192\\ 
17\\
0\\
\end{matrix}
\end{pmatrix}=
M\begin{vmatrix}
0 & 0 & -64 \\ 
0 & 7 & 1 \\ 
1 & 1 & -1\\
\end{vmatrix}=-64\cdot 7 \cdot 1 = -448\ne 0 \Rightarrow rank~\tilde A = 3$ 

4) Так как $rank~A = rank~\tilde A = n = 3\Rightarrow$ система совместна и имеет единственное решение.

In [11]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0]).reshape(-1, 1)
gauss_method(A, b, 3)

rank(A): 3

rank(A_ext): 3

N of vars: 3



'Cистема совместна и имеет единственное решение'

    
### б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{pmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9\\
\end{pmatrix};~~~~
\tilde A = \begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
1\\ 
-2\\
5\\
\end{matrix}
\end{pmatrix}$

2) Найдем ранг матрицы коэффициентов $A$. Приведем матрицу к треугольному виду:<br>

- В данной матрице все строки пропорциональны - 3-я строка является суммой 1-й и 2-й, следовательно первые две строки можно вычеркнуть:
### $\begin{vmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9 \\
\end{vmatrix}=
\begin{vmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
2+1 & -2+(-4) & 6+3 \\
\end{vmatrix}=
\begin{vmatrix}
3 & -6 & 9\\
\end{vmatrix}$

- Полученная матрица имеет размерность $1\times 3$. Минором в данном случае является элемент на пересечении строки и столбца. Наивысший порядок минора (из возможных миноров) равен 1 и равен элементу строки:<br>
### $M\begin{vmatrix} 3 & -6 & 9\\ \end{vmatrix}=9\ne 0 \Rightarrow rank~A = 1$ 

3) Найдем ранг расширенной матрицы $\tilde A$. Приведем матрицу к треугольному виду. Работаем только со строками:<br>

- Первая и вторая строки пропорциональны. Если умножить 2-ю строку на 2 можно получить первую (кроме 4 столбца). Таким образом мы можем вычеркнуть первую строку:
### $\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
1\\ 
-2\\
5\\
\end{matrix}
\end{pmatrix}=
\begin{bmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
-2\\
5
\end{matrix}
\end{bmatrix}$

- Умножим 1-ую строку на (-3). Добавим 2-ую строку к 1-ой::<br>
### $\begin{bmatrix}
\left.\begin{matrix}
((-3)\cdot 1)+3 & ((-3)\cdot (-2))+(-6) & ((-3)\cdot 3)+9 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
((-3)\cdot (-2))+5\\
5
\end{matrix}
\end{bmatrix}=
\begin{bmatrix}
\left.\begin{matrix}
0 & 0 & 0 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
11\\
5
\end{matrix}
\end{bmatrix}$

- Полученная матрица имеет размерность $2\times 4$. Найдем ненулевой минор наибольшего порядка:<br>
### $\tilde M
\begin{bmatrix}
\left.\begin{matrix}
0 & 0 & 0 \\ 
3 & -6 & 9\\
\end{matrix}
\right|\begin{matrix}
11\\
5
\end{matrix}
\end{bmatrix}=
\begin{vmatrix}
0 & 11 \\ 
9 & 5\\
\end{vmatrix}=11\cdot 9 = 99\ne 0 \Rightarrow rank~\tilde A = 2$<br>
Наивысший порядок минора (из возможных миноров) равен 2.<br>

4) Так как $rank~A < rank~\tilde A \Rightarrow$ система несовместна и не имеет решений.

In [12]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
gauss_method(A, b, 3)

rank(A): 1

rank(A_ext): 2

N of vars: 3



'Cистема несовместна и не имеет решений'

### в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{bmatrix}
1 & 2 & 5 \\ 
3 & 1 & -8\\
\end{bmatrix};~~~~
\tilde A = \begin{bmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8\\
\end{matrix}
\right|\begin{matrix}
4\\ 
-2
\end{matrix}
\end{bmatrix}$

2) Найдем ранг матрицы коэффициентов $A$. Приведем матрицу к ступенчатому виду:<br>

- Умножим 1-ую строку на (-3). Добавим 1-ую строку ко 2-ой:
### $\begin{bmatrix}
-3 \cdot 1 & -3 \cdot 2 & -3 \cdot 5 \\ 
-3+3 & -6+1 & (-15)+(-8)\\
\end{bmatrix}=
\begin{bmatrix}
1 & 2 & 5 \\ 
0 & -5 & -23\\
\end{bmatrix}$

- Разделим 2-ую строку на (-5):<br>
### $\begin{bmatrix}
1 & 2 & 5 \\ 
0\div -5 & -5\div -5 & -23\div -5\\
\end{bmatrix}=
\begin{bmatrix}
1 & 2 & 5 \\ 
0 & 1 & \frac{23}{5}\\
\end{bmatrix}$

- Полученная матрица имеет размерность $2\times 3$. Наивысший порядок минора (из возможных миноров) равен 2:<br>
### $M\begin{bmatrix}
1 & 2 & 5 \\ 
0 & 1 & \frac{23}{5}\\
\end{bmatrix}=
M\begin{vmatrix}
2 & 5 \\ 
1 & \frac{23}{5}\\
\end{vmatrix}=2\cdot \frac{23}{5} = \frac{46}{5} \ne 0 \Rightarrow rank~A = 2$ 

3) Найдем ранг расширенной матрицы $\tilde A$. Приведем матрицу к ступенчатому виду:<br>

- Умножим 1-ую строку на (-3). Добавим 1-ую строку ко 2-ой:
### $\begin{bmatrix}
\left.\begin{matrix}
-3 \cdot 1 & -3 \cdot 2 & -3 \cdot 5 \\ 
-3+3 & -6+1 & (-15)+(-8)\\
\end{matrix}
\right|\begin{matrix}
-3 \cdot 4\\ 
-2 +(-12)
\end{matrix}
\end{bmatrix}=
\begin{bmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & -5 & -23\\
\end{matrix}
\right|\begin{matrix}
4\\ 
-14
\end{matrix}
\end{bmatrix}$

- Разделим 2-ую строку на (-5):<br>
### $\begin{bmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0\div -5 & -5\div -5 & -23\div -5\\
\end{matrix}
\right|\begin{matrix}
4\\ 
-14\div -5
\end{matrix}
\end{bmatrix}=
\begin{bmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & 1 & \frac{23}{5}\\
\end{matrix}
\right|\begin{matrix}
4\\ 
\frac{14}{5}
\end{matrix}
\end{bmatrix}$

- Полученная матрица имеет размерность $2\times 3$. Наивысший порядок минора (из возможных миноров) равен 2:<br>
### $\tilde M\begin{bmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & 1 & \frac{23}{5}\\
\end{matrix}
\right|\begin{matrix}
4\\ 
\frac{14}{5}
\end{matrix}
\end{bmatrix}=
M\begin{vmatrix}
5 & 4 \\ 
\frac{23}{5} & \frac{14}{5}\\
\end{vmatrix}=5\cdot \frac{14}{5} = \frac{\not 5 \cdot 14}{\not 5}=14 \ne 0 \Rightarrow rank~A = 2$ 

4) Так как $rank~A = rank~\tilde A = 2 < n = 3\Rightarrow$ система совместна и имеет бесконечное количество решений.

In [13]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
gauss_method(A, b, 3)

rank(A): 2

rank(A_ext): 2

N of vars: 3



'Cистема совместна и имеет бесконечное количество решений'

__Ответ:__<br>
__a)__ Система совместна и имеет единственное решение;<br>
__б)__ Система несовместна и не имеет решений;<br>
__в)__ Система совместна и имеет бесконечное количество решений.<br>

### 3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

### $\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{pmatrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{pmatrix};~~~~
\tilde A = \begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}
\right|\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

2) Найдем ранг матрицы коэффициентов $A$. Приведем матрицу к треугольному виду:<br>
- Для удобства вычислений поменяем строки местами - 1-ю и 4-ю, затем 2-ю и 3-ю:
### $\begin{pmatrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 0 & 2\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
1 & 3 & -2 & 4
\end{pmatrix}=
\begin{pmatrix}
0 & 0 & 0 & 2\\ 
0 & 0 & 3 & 0\\ 
0 & 5 & 0 & 1\\ 
1 & 3 & -2 & 4
\end{pmatrix}$

- В результате преобразований получили матрицу размером $4\times 4$, которая является для себя минором наивысшего порядка (из возможных миноров). Минор равен произведению элементов побочной диагонали:<br>
### $M=\begin{vmatrix}
0 & 0 & 0 & 2\\ 
0 & 0 & 3 & 0\\ 
0 & 5 & 0 & 1\\ 
1 & 3 & -2 & 4
\end{vmatrix}=1\cdot 5 \cdot 3 \cdot 2 = 30\ne 0 \Rightarrow rank~A = 4$ 

3) Найдем ранг расширенной матрицы $\tilde A$. Приведем матрицу к треугольному виду:<br>
- Для удобства вычислений поменяем строки местами - 1-ю и 4-ю, затем 2-ю и 3-ю:
### $\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}
\right|\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & 0 & 2\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
1 & 3 & -2 & 4
\end{matrix}
\right|\begin{matrix}
1\\ 
2\\
4\\
3
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & 0 & 2\\ 
0 & 0 & 3 & 0\\ 
0 & 5 & 0 & 1\\ 
1 & 3 & -2 & 4
\end{matrix}
\right|\begin{matrix}
1\\ 
4\\
2\\
3
\end{matrix}
\end{pmatrix}$

- В результате преобразований получили матрицу размером $4\times 4$. Минор наивысшего порядка (из возможных миноров) является матрицей коэффициентов $A$. Минор равен произведению элементов побочной диагонали:<br>
### $\tilde M=\begin{pmatrix}
\left.\begin{matrix}
0 & 0 & 0 & 2\\ 
0 & 0 & 3 & 0\\ 
0 & 5 & 0 & 1\\ 
1 & 3 & -2 & 4
\end{matrix}
\right|\begin{matrix}
1\\ 
4\\
2\\
3
\end{matrix}
\end{pmatrix}=
M=\begin{vmatrix}
0 & 0 & 0 & 2\\ 
0 & 0 & 3 & 0\\ 
0 & 5 & 0 & 1\\ 
1 & 3 & -2 & 4
\end{vmatrix}=1\cdot 5 \cdot 3 \cdot 2 = 30\ne 0 \Rightarrow rank~\tilde A = 4$ 

4) Так как $rank~A = rank~\tilde A = n = 4\Rightarrow$ система совместна и имеет единственное решение.

In [14]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1]).reshape(-1, 1)
gauss_method(A, b, 4)

rank(A): 4

rank(A_ext): 4

N of vars: 4



'Cистема совместна и имеет единственное решение'

__Ответ:__<br>
Система совместна и имеет единственное решение.

### 4. Дана система линейных уравнений, заданная расширенной матрицей

### $\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение:__<br>

1) Система несовместна при $rank~A < rank~\tilde A$. Найдем ранг расширенной матрицы $\tilde A$. Приведем матрицу к ступенчатому виду:<br>

- От 2-й строки отнимаем 1-ю строку, умноженную на 4:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4-(4\cdot 1) & 5-(4\cdot 2) & 6-(4\cdot 3)\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4\cdot a\\
c
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c
\end{matrix}
\end{pmatrix}$

- От 3-й строки отнимаем 1-ю строку, умноженную на 7:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7-(7\cdot 1) & 8-(7\cdot 2) & 9-(7\cdot 3)
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7\cdot a
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$

- 2-ю строку делим на -3:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 \div (-3) & -6 \div (-3)\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
(b-4a) \div (-3)\\
c-7a
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
-\frac{b}{3}+\frac{4a}{3}\\
c-7a
\end{matrix}
\end{pmatrix}$

- К 3-й строке добавляем 2-ю строку, умноженную на 6:

### $\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & -6+(6 \cdot 1) & -12+(6 \cdot 2)
\end{matrix}\right|
\begin{matrix}
a\\ 
-\frac{b}{3}+\frac{4a}{3}\\
c-7a+\bigg( 6 \cdot \left( -\frac{b}{3}+\frac{4a}{3}\right)\bigg)=c-7a- \frac{\not 6~2 \cdot b}{\not 3}+\frac{\not 6~2 \cdot 4 a}{\not 3} = c-7a-2b+8a
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
-\frac{b}{3}+\frac{4a}{3}\\
c+a-2b 
\end{matrix}
\end{pmatrix}$

Если в результате преобразований $c+a-2b\ne 0$, тогда систем будет несовместна.

__Ответ:__<br>
Система несовместна при $c+a-2b\ne 0$.

# Урок 7

# Системы линейных уравнений. Часть 2

## Практическое задание

### 1. Решить систему уравнений методом Крамера:

### а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{bmatrix}
1 & -2 \\ 
3 & -4\\
\end{bmatrix};~~~~
\tilde A = \begin{bmatrix}
\left.\begin{matrix}
1 & -2 \\ 
3 & -4\\
\end{matrix}
\right|\begin{matrix}
1\\ 
7
\end{matrix}
\end{bmatrix}$

2) Найдем определитель матрицы коэффициентов:<br>
### $det A=
\begin{vmatrix}
1 & -2 \\
3 & -4
\end{vmatrix}=\Big(1 \cdot \left(-4\right)\Big)-\Big(3 \cdot \left(-2\right)\Big)=-4-\left(-6\right)=2\ne 0$<br>
Следовательно система совместна и имеет единственное решение.

3) Найдем определители $detA_{1}$, $detA_{2}$:<br>
### $det A_{1}=
\begin{vmatrix}
1 & -2 \\
7 & -4
\end{vmatrix}=\Big(1 \cdot \left(-4\right)\Big)-\Big(7 \cdot \left(-2\right)\Big)=-4-\left(-14\right)=10$<br>
### $det A_{2}=
\begin{vmatrix}
1 & 1 \\
3 & 7
\end{vmatrix}=\Big(1 \cdot \left(7\right)\Big)-\Big(3 \cdot \left(1\right)\Big)=7-3=4$<br>

3) Найдем решение по формулам Крамера:<br>
### $x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5;$<br>
### $x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2.$

In [26]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).reshape(-1, 1)
x_1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1)))) /  np.linalg.det(A)
x_2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b))) /  np.linalg.det(A)

print(f'A: {A}\n')
print(f'b: {b}\n')
print(f'x_1 = {x_1}\n')
print(f'x_2 = {x_2}\n')

A: [[ 1 -2]
 [ 3 -4]]

b: [[1]
 [7]]

x_1 = 4.999999999999998

x_2 = 1.9999999999999996



In [25]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

    
### б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение:__<br>

1) Запишем систему в виде матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$:<br>
### $A=\begin{bmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1 \\
\end{bmatrix};~~~~
\tilde A = \begin{bmatrix}
\left.\begin{matrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1 \\
\end{matrix}
\right|\begin{matrix}
10 \\ 
-2 \\
1
\end{matrix}
\end{bmatrix}$

2) Найдем определитель матрицы коэффициентов, разложив по 1 строке:<br>
### $det A=
\begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1 \\
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
\left(-1\right)\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=$
### $=2\cdot \Big(1 \cdot 1-\left(-3\right)\cdot 4\Big)+\Big(1\cdot 1-\left(-3\right)\cdot 2\Big)+5\cdot \Big(1\cdot 4-2\cdot 1\Big)=26+7+10=43\neq 0$
Следовательно система совместна и имеет единственное решение.

3) Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:<br>
### $detA_{1}=
\begin{vmatrix}
10 & -1 & 5 \\ 
-2 & 1 & -3 \\ 
1 & 4 & 1 \\
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
\left(-1\right)\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=$
### $=10 \cdot \Big( 1 \cdot 1 - \left( -3 \right) \cdot 4 \Big) + \Big( \left( -2 \right) \cdot 1 - \left( -3 \right) \cdot 1 \Big) + 5 \cdot \Big( \left( -2 \right) \cdot 4 - 1 \cdot 1 \Big) = 130+1-45=86$<br>

### $detA_{2}=
\begin{vmatrix}
2 & 10 & 5 \\ 
1& -2 & -3 \\ 
2 & 1 & 1 \\
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+
5\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=$
### $ = 2 \cdot \Big( \left( -2 \right) \cdot 1 - \left( -3 \right) \cdot 1 \Big) - 10 \cdot \Big( 1 \cdot 1 - \left( -3 \right) \cdot 2 \Big) + 5 \cdot \Big( 1 \cdot 1 - \left( -2 \right) \cdot 2 \Big)=2-70+25=-43$<br>

### $detA_{3}=
\begin{vmatrix}
2 & -1 & 10 \\ 
1 & 1 & -2 \\ 
2 & 4 & 1 \\
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1 
\end{vmatrix}-
\left(-1\right)\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=$
### $=2 \cdot \Big( 1 \cdot 1 - \left( -2 \right) \cdot 4 \Big) + \Big( 1 \cdot 1 - \left( -2 \right) \cdot 2 \Big) + 10 \cdot \Big( 1 \cdot 4 - 2 \cdot 1 \Big) = 18+5+20=43$<br>

3) Найдем решение по формулам Крамера:<br>
### $x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2;$
### $x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1;$
### $x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$

In [27]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)
x_1 = np.linalg.det(np.hstack((b, A[:,1:]))) /  np.linalg.det(A)
x_1 = np.linalg.det(np.hstack((b, A[:,1:]))) /  np.linalg.det(A)
x_2 = np.linalg.det(np.hstack((A[:,:1], b, A[:,-1:]))) /  np.linalg.det(A)
x_3 = np.linalg.det(np.hstack((A[:,:2], b))) /  np.linalg.det(A)

print(f'A: {A}\n')
print(f'b: {b}\n')
print(f'x_1 = {x_1}\n')
print(f'x_2 = {x_2}\n')
print(f'x_3 = {x_3}\n')

A: [[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b: [[10]
 [-2]
 [ 1]]

x_1 = 2.0000000000000018

x_2 = -1.0000000000000009

x_3 = 1.0



In [28]:
np.linalg.solve(A, b)

array([[ 2.],
       [-1.],
       [ 1.]])

### $^{*}$2. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

### а) $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

__Решение:__<br>

1) Запишем матрицу $L$:<br>
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

Для получения коэффициентов $l_{21}$, $l_{31}$, и $l_{32}$ матрицы $L$ проведем прямой метод Гаусса для матрицы коэффициентов.

2) Умножим 1-ю строку на 2 и вычтем из 2-й строки. Внесём коэффициент $l_{21}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 2 & 4 \\ 
2-(1 \cdot 2) & 9-(2 \cdot 2) & 12-(4 \cdot 2) \\ 
3 & 26 & 30
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

3) Умножим 1-ю строку на 3 и вычтем из 3-й строки. Внесём коэффициент $l_{31}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3-(1 \cdot 3) & 26-(2 \cdot 3) & 30-(4 \cdot 3) 
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 18
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$

4) Умножим 2-ю строку на 4 и вычтем из 3-й строки. Внесём коэффициент $l_{32}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0-(0 \cdot 4) & 20-(5 \cdot 4) & 18-(4 \cdot 4) 
\end{pmatrix} \Rightarrow~~~
U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

    
### б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

__Решение:__<br>

1) Запишем матрицу $L$:<br>
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
l_{21} & 1 & 0 & 0\\ 
l_{31} & l_{32} & 1 & 0 \\
l_{41} & l_{42} & l_{43} & 0
\end{pmatrix}$

Для получения коэффициентов $l_{21}$, $l_{31}$, $l_{32}$, $l_{41}$, $l_{42}$ и $l_{43}$ матрицы $L$ проведем прямой метод Гаусса для матрицы коэффициентов.

2) Умножим 1-ю строку на 2 и вычтем из 2-й строки. Внесём коэффициент $l_{21}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2-(1 \cdot 2) & 5-(1 \cdot 2) & 8-(2 \cdot 2) & 9-(4 \cdot 2)\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
l_{31} & l_{32} & 1 & 0 \\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$

3) Умножим 1-ю строку на 3 и вычтем из 3-й строки. Внесём коэффициент $l_{31}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3-(1 \cdot 3) & 18-(1 \cdot 3) & 29-(2 \cdot 3) & 18-(4 \cdot 3)\\
4 & 22 & 53 & 33
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0 \\
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix}$

4) Умножим 1-ю строку на 4 и вычтем из 4-й строки. Внесём коэффициент $l_{41}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4-(1 \cdot 4) & 22-(1 \cdot 4) & 53-(2 \cdot 4) & 33-(4 \cdot 4)
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$

5) Умножим 2-ю строку на 5 и вычтем из 3-й строки. Внесём коэффициент $l_{32}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0-(0 \cdot 5) & 15-(3 \cdot 5) & 23-(4 \cdot 5) & 6-(1 \cdot 5)\\
0 & 18 & 45 & 17 
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$

6) Умножим 2-ю строку на 6 и вычтем из 4-й строки. Внесём коэффициент $l_{42}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0-(0 \cdot 6) & 18-(3 \cdot 6) & 45-(4 \cdot 6) & 17-(1 \cdot 6) 
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1
\end{pmatrix}$

7) Умножим 3-ю строку на 7 и вычтем из 4-й строки. Внесём коэффициент $l_{43}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0-(0 \cdot 7) & 0-(0 \cdot 7) & 21-(3 \cdot 7) & 11-(1 \cdot 7) 
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$

__Ответ:__<br>
### __a)__ $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$
### __б)__ $L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$

    
### $^{*}$3. Решить систему линейных уравнений методом $LU$-разложения:

### $\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

__Решение:__<br>

1) Запишем систему уравнений в виде матрицы коэффициентов, свободных членов и матрицы $L$:
### $A=\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix};~~~~
b=\begin{pmatrix}
1 \\ 
-6 \\ 
-5
\end{pmatrix};~~~~
L=\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$<br>
Для получения коэффициентов $l_{21}$, $l_{31}$, и $l_{32}$ матрицы $L$ проведем прямой метод Гаусса для матрицы коэффициентов.

2) Умножим 1-ю строку на $\frac{11}{2}$ и вычтем из 2-й строки. Внесём коэффициент $l_{21}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
2 & 1 & 3 \\ 
11-\left(\not2\cdot\frac{11}{\not 2}\right) & 7-\left(1\cdot\frac{11}{2}\right) & 5-\left(3\cdot\frac{11}{2}\right) \\ 
9 & 8 & 4
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
11-11 & \frac{14}{2}-\frac{11}{2} & \frac{10}{2}-\frac{33}{2} \\ 
9 & 8 & 4
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
9 & 8 & 4
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix}$

3) Умножим 1-ю строку на $\frac{9}{2}$ и вычтем из 3-й строки. Внесём коэффициент $l_{31}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
9-\left(\not 2 \cdot \frac{9}{\not 2}\right) & 8-\left(1 \cdot \frac{9}{2}\right) & 4-\left(3 \cdot \frac{9}{2}\right)
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
9-9 & \frac{16}{2} - \frac{9}{2} & \frac{8}{2} - \frac{27}{2}
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & l_{32} & 1
\end{pmatrix}$

4) Умножим 2-ю строку на $\frac{14}{6}$ и вычтем из 3-й строки. Внесём коэффициент $l_{32}$ в матрицу $L$:<br>
### $U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0-\left(0\cdot\frac{14}{6}\right) & \frac{7}{2}-\left(\frac{3}{2} \cdot \frac{14}{6}\right) & -\frac{19}{2}-\left(-\frac{23}{2} \cdot \frac{14}{6}\right)
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0-0 & \frac{7}{2}-\frac{\not4\not2~~7}{\not1\not2~~2} & -\frac{57}{6}+\frac{161}{6}
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$
### $L=\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{14}{6} & 1
\end{pmatrix}$

5) Решим систему $Ly=b$:<br>
### $\begin{cases}
y_{1}=1 \\
\frac{11}{2}y_{1}+y_{2}=-6 \\
\frac{9}{2}y_{1}+\frac{14}{6}y_{2}+y_{3}=-5
\end{cases}$
### $y_{2}=-6-\frac{11}{2}y_{1}=-6-\left(\frac{11}{2}\cdot1\right)=-\frac{12}{2}-\frac{11}{2}=-\frac{23}{2}$
### $y_{3}=-5-\frac{9}{2}y_{1}-\frac{14}{6}y_{2}=-5-\left(\frac{9}{2}\cdot1\right)-\Big(\frac{14}{6}\cdot\left(-\frac{23}{2}\right)\Big)=-\frac{10}{2}-\frac{9}{2}-\left(-\frac{161}{6}\right)=-\frac{57}{6}+\frac{161}{6}=\frac{52}{3}$
### $\begin{cases}
y_{1}=1 \\
y_{2}=-\frac{23}{2} \\
y_{3}=\frac{52}{3}
\end{cases}$

6) Решим систему $Ux=y$:<br>
### $\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=-\frac{23}{2} \\
\frac{52}{3}x_{3}=\frac{52}{3}
\end{cases}$
### $x_{3}=\frac{52}{3}\div\frac{52}{3}=\frac{\not5\not2}{\not3}\times\frac{\not3}{\not5\not2}=1$
### $\frac{3}{2}x_{2}=-\frac{23}{2}+\frac{23}{2}x_{3}=-\frac{23}{2}+\left(\frac{23}{2}\cdot1\right)=0~~~~~\Rightarrow~~~~~x_{2}=0\div\frac{3}{2}=0$
### $2x_{1}=1-x_{2}-3x_{3}=1-0-\left(3\cdot1\right)=-2~~~~~\Rightarrow~~~~~x_{1}=-2\div2=-1$
### $\begin{cases}
x_{1}=-1 \\
x_{2}=0 \\
x_{3}=1
\end{cases}$

7) Произведем проверку, подставив полученные значения переменных в исходную систему:<br>
### $\begin{cases}
2\cdot (-1)+0+3\cdot 1=-2+3=1 \\
11\cdot (-1)+7\cdot0+5\cdot 1=-11+5=-6 \\
9\cdot (-1)+8\cdot0+4\cdot 1=-9+4=-5
\end{cases}$

Таким образом, найденное решение верно.

__Ответ:__<br>
### $x_{1}=-1;~~~x_{2}=0;~~~x_{3}=1$.

### $^{*}$4. Решить систему линейных уравнений методом Холецкого:

### $\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

__Решение:__<br>

1) Запишем систему уравнений в виде матрицы коэффициентов, свободных членов и матрицы $L$:
### $A=\begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix};~~~~
b=\begin{pmatrix}
531 \\ 
-460 \\ 
193
\end{pmatrix};~~~~
L=\begin{pmatrix}
l_{11} & 0 & 0 \\ 
l_{21} & l_{22} & 0 \\ 
l_{31} & l_{32} & l_{33}
\end{pmatrix}$<br>

2) Получим ненулевые элементы матрицы $L$ с помощью формул:
### $l_{11}=\sqrt{a_{11}}=\sqrt{81}=9$
### $l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5$
### $l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5$
### $l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - (-5)^2}=\sqrt{25}=5$
### $l_{32}=\frac{1}{l_{22}}\left(a_{32}-l_{21}\cdot l_{31}\right)=\frac{1\cdot\big(-15-\left(-5\cdot5\right)\big)}{5}=\frac{10}{5}=2$
### $l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-5^2-2^2}=\sqrt{9}=3$

3) Запишем полученные элементы в матрицу $L$ и получим из нее матрицу $L^T$:
### $L=\begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix};~~~~~~~~
L^T=\begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}$

4) Решим систему $Ly=b~$:
### $\begin{cases}
9y_{1}=531 \\
-5y_{1}+5y_{2}=-460 \\
5y_{1}+2y_{2}+3y_{3}=193
\end{cases}$
### $y_{1}=\frac{531}{9}=59$
### $5y_{2}=-460+5y_{1}=-460+5\cdot59=-460+295=-165~~~~~\Rightarrow~~~~~y_{2}=\frac{-165}{5}=-33$
### $3y_{3}=193-5y_{1}-2y_{2}=193-5\cdot59-2\cdot(-33)=193-295+66=-36~~~~~\Rightarrow~~~~~y_{3}=\frac{-36}{3}=-12$
### $\begin{cases}
y_{1}=59 \\
y_{2}=-33 \\
y_{3}=-12
\end{cases}$

5) Решим систему $L^{T}x=y~$:
### $\begin{cases}
9x_1-5x_2+5x_3=59 \\
5x_2+2x_3=-33 \\
3x_{3}=-12
\end{cases}$
### $x_{3}=-12\div3=-4$
### $5x_{2}=-33-2x_{3}=-33-\big(2\cdot(-4)\big)=-25~~~~~\Rightarrow~~~~~x_{2}=-25\div5=-5$
### $9x_{1}=59+5x_{2}-5x_{3}=59+\big(5\cdot(-5)\big)-\big(5\cdot(-4)\big)=59-25+20=54~~~~~\Rightarrow~~~~~x_{1}=54\div9=6$
### $\begin{cases}
x_{1}=6 \\
x_{2}=-5 \\
x_{3}=-4
\end{cases}$

6) Произведем проверку, подставив полученные значения переменных в исходную систему:<br>
### $\begin{cases}
81\cdot6-45\cdot(-5)+45\cdot(-4)=486+225-180=531 \\
-45\cdot6+50\cdot(-5)-15\cdot(-4)=-270-250+60=-460 \\
45\cdot6-15\cdot(-5)+38\cdot(-4)=270+75-152=193
\end{cases}$

Таким образом, найденное решение верно.

__Ответ:__<br>
### $x_{1}=6;~~~x_{2}=-5;~~~x_{3}=-4$.

### $^{*}$5. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [34]:
A = np.array([[ 2., 1., 3.],
              [11., 7., 5.],
              [9., 8., 4.]])

b = np.array([ 1., -6., -5.])

Acpy = np.copy(A)
bcpy = np.copy(b)

n = len(b)

print(A)
print(b)
print('')

for k in range(0, n-1):
    for i in range(k+1, n):
        ratio = A[i, k]/A[k, k]
        for j in range(k, n):
            A[i, j] -= ratio*A[k, j]
        b[i] -= ratio*b[k]

print(A)
print(b)

x = np.zeros(n)

x[n-1] = b[n-1]/A[n-1, n-1]
for i in range(n-2, -1, -1):
    sum_j = 0
    for j in range(i+1, n):
        sum_j += A[i, j]*x[j]
    x[i] = (b[i] - sum_j)/A[i, i]
    
print(A)
print(b)
print(x)

print(Acpy)
print(bcpy)

print(np.dot(Acpy, x) - bcpy)

[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]
[ 1. -6. -5.]

[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
[  1.         -11.5         17.33333333]
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
[  1.         -11.5         17.33333333]
[-1.  0.  1.]
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]
[ 1. -6. -5.]
[0. 0. 0.]
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]


## Литература

1. Ильин В. А., Позняк Э. Г. Линейная алгебра: Учеб. для вузов. — 6-е изд. — М.: Физматлит, 2005.

2. Фаддеев Д. К., Фаддеева В. Н. Вычислительные методы линейной алгебры. М.: ГИФМЛ, 1960.

3. Рябушко А. П., Сборник индивидуальных заданий по высшей математике. Часть 1. Минск: Вышэйшая школа, 1990.

4. Форсайт Дж., Молер К. Численное решение систем линейных алгебраических уравнений. М.: Мир, 1969.

## Дополнительные материалы

1. Островский А. М. Решение уравнений и систем уравнений. М.: Издательство иностранной литературы, 1963.
2. [Критерий положительной определенности матрицы](http://twt.mpei.ac.ru/math/LARB/Quadrf/LA_06030300.html).
3. [Доказательство правила Крамера](http://portal.tpu.ru/SHARED/k/KONVAL/Sites/Russian_sites/2/18.htm).