# Урок 8

# Сингулярное разложение матриц

## Практическое задание

### 1. Найти с помощью NumPy SVD для матрицы:
### $A=\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}$

__Решение:__<br>

In [15]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}', "\n")


U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print(f'Матрица D:\n{D}', "\n")
print(f'Матрица U:\n{U}', "\n")
print(f'Матрица V:\n{V}', "\n")
print(f'Матрица V.T = W:\n{W}', "\n")

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]] 

Матрица D:
[[8.8249 0.     0.    ]
 [0.     6.1406 0.    ]
 [0.     0.     2.5327]
 [0.     0.     0.    ]
 [0.     0.     0.    ]] 

Матрица U:
[[ 0.1706  0.1568 -0.5308 -0.7991 -0.1616]
 [ 0.3929 -0.5293  0.6135 -0.4338  0.0308]
 [-0.1437 -0.8245 -0.5238  0.1405  0.074 ]
 [ 0.8884  0.0607 -0.2466  0.3776 -0.0604]
 [ 0.0813  0.1083 -0.0823 -0.1052  0.9817]] 

Матрица V:
[[ 0.0712 -0.3674 -0.9273]
 [ 0.717   0.6651 -0.2085]
 [ 0.6934 -0.6501  0.3108]] 

Матрица V.T = W:
[[ 0.0712  0.717   0.6934]
 [-0.3674  0.6651 -0.6501]
 [-0.9273 -0.2085  0.3108]] 



Проверим правильность решения умножив полученные матицы:<br>
### $U\cdot D\cdot V^T=A$ 

In [12]:
print(f'Проверка правильности решения:\n{np.dot(np.dot(U, D), V.T)}', "\n")

Проверка правильности решения:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]] 



### 2. Для матрицы из предыдущего задания найти:
__а) норму Евклида__

__Решение:__<br>

Так как мы имеем $SVD$-разложение, то норма Евклида для матрицы матрицы $A$ будет равна первому диагональному элементу матрицы $D$:<br>
### $\left \| A \right \|_{E}=\text{max}D=\mu_{1}=D_{11}=8,8249$

В NumPy можно получить норму Евклида следующим образом:

In [21]:
print(f'‖𝐴‖_𝐸:  {np.linalg.norm(A, ord=2)}', "\n")
print(f'‖𝐴‖_𝐸:  {D[0,0]}', "\n")

‖𝐴‖_𝐸:  8.824868854820444 

‖𝐴‖_𝐸:  8.824868854820442 



__б) норму Фробениуса__

__Решение:__<br>

Найдем норму Фробениуса разными способами:<br>
### $\left \| A \right \|_{F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}=$
### $=\sqrt{1^2+2^2+0^2+0^2+0^2+5^2+3^2+(-4)^2+2^2+1^2+6^2+5^2+0^2+1^2+0^2}=\sqrt{122}=11,045361$

### $\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}=\sqrt{8,8249^2+6,1406^2+2,5327^2}=$
### $\sqrt{77,87886001+37,70696836+6,41456929}=\sqrt{122,00039766}=11,045379$

In [33]:
frob_norm = 0
for i in range(np.linalg.matrix_rank(A)):
    frob_norm += s[i]**2
frob_norm = np.sqrt(frob_norm)
print(f'‖𝐴‖_F:  {frob_norm}', "\n")

‖𝐴‖_F:  11.045361017187261 



In [34]:
print(f'‖𝐴‖_F:  {np.linalg.norm(A)}', "\n")

‖𝐴‖_F:  11.045361017187261 



__Ответ:__<br>
### $\left \| A \right \|_{E}=8,8249$
### $\left \| A \right \|_{F}=11,045361$

## Литература

 1. Форсайт Дж., Молер К. Численное решение систем линейных алгебраических
уравнений. М.: Мир, 1969.
 2. Форсайт Дж., Малькольм М., Моулер К. Машинные методы математических
вычислений. М.: Мир, 1980.
 3. Голуб Дж., Ван-Лоун Ч. Матричные вычисления. М.: Мир, 1999.
 4. Логинов Н. В. Сингулярное разложение матриц. М.: Мир, 1996.
 5. Хорн Р., Джонсон Ч. Матричный анализ. М.: Мир, 1989.

1. [SVD в NumPy](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.linalg.svd.html).