## Вычисления с помощью Numpy

### Задание 1<br>
Импортируйте библиотеку $\mathsf{\color{darkblue}{Numpy}}$ и дайте ей псевдоним np.
Создайте массив $\mathsf{\color{darkblue}{Numpy}}$ под названием $\mathbf{\color{blue}{a}}$ размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод $\mathbf{\color{green}{mean}}$ массива $\mathsf{\color{darkblue}{Numpy}}$. Результат запишите в массив $\mathbf{\color{blue}{mean\underline{\;} a}}$, в нем должно быть 2 элемента.<br>
__Решение:__<br>

In [8]:
import numpy as np
import pandas as pd

In [9]:
a = np.transpose(np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]]))
print(f'Массив a:\n{a}')

Массив a:
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [10]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

### Задание 2<br>
Вычислите массив $\mathbf{\color{blue}{a\underline{\;} centered}}$, отняв от значений массива “$\mathbf{\color{blue}{a}}$” средние значения соответствующих признаков, содержащиеся в массиве $\mathbf{\color{blue}{mean\underline{\;} a}}$. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.<br>
__Решение:__<br>

In [11]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3<br>
Найдите скалярное произведение столбцов массива $\mathbf{\color{blue}{a\underline{\;} centered}}$. В результате должна получиться величина $\mathbf{\color{blue}{a\underline{\;} centered\underline{\;} sp}}$. Затем поделите $\mathbf{\color{blue}{a\underline{\;} centered\underline{\;} sp}}$ на N-1, где N - число наблюдений.<br>
__Решение:__<br>


In [12]:
a_centered_sp = (a_centered[:, 0] @ a_centered[:, 1])
a_centered_sp

8.0

In [13]:
N_1 = a_centered.shape[0] - 1
N_1

4

In [14]:
a_centered_sp / N_1

2.0

### Задание 4*<br>
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “$\mathbf{\color{blue}{a}}$”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.<br>
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции $\mathbf{\color{green}{np.cov}}$. В качестве аргумента m функция $\mathbf{\color{green}{np.cov}}$ должна принимать транспонированный массив “$\mathbf{\color{blue}{a}}$”. В получившейся ковариационной матрице (массив $\mathsf{\color{darkblue}{Numpy}}$ размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.<br>
__Решение:__<br>

In [15]:
m = a.transpose()
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [16]:
t = np.cov(m)
t

array([[1. , 2. ],
       [2. , 4.3]])

In [17]:
t[0, 1]

2.0

## Работа с данными в Pandas

### Задание 1<br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'], [450, 300, 350, 500, 450, 370, 290].
__Решение:__<br>

### Задание 2<br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'], [450, 300, 350, 500, 450, 370, 290].
__Решение:__<br>

### Задание 3<br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'], [450, 300, 350, 500, 450, 370, 290].
__Решение:__<br>

### Задание 4<br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'], [450, 300, 350, 500, 450, 370, 290].
__Решение:__<br>

### Задание 5*<br>
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:
[1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'], [450, 300, 350, 500, 450, 370, 290].
__Решение:__<br>